FROM mysql:5.7

ENV MYSQL_ROOT_PASSWORD=root

ENV MYSQL_DATABASE=powerload
ENV MYSQL_USER=lowerload
ENV MYSQL_PASSWORD=secret
ENV MYSQL_ALLOW_EMPTY_PASSWORD=no
ENV MYSQL_RANDOM_ROOT_PASSWORD=no
ENV MYSQL_HOST=localhost

EXPOSE 3306